<a href="https://colab.research.google.com/github/gitae-lee/mini-project1/blob/master/1006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 소개

https://numpy.org/doc/stable/user/whatisnumpy.html

In [ ]:
ls =[[1,2,3,4],[3,4,5],[2,3],[1],1,2,'Hello']
ls

[[1, 2, 3, 4], [3, 4, 5], [2, 3], [1], 1, 2, 'Hello']

In [ ]:
#numpy 모듈을 사용하기 위한 import문
import numpy as np

In [ ]:
ls = [1,2,3,4,5]
arr = np.array(ls)
print(arr)
print(type(arr)) #다차원 배열을 표현하는 타입이 ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
ls1 = [1,2,3]
ls2 = [4,7,2]
ls3 = ls1+ls2
print(ls3)#파이썬 리스트의 합은 concat

[1, 2, 3, 4, 7, 2]


In [ ]:
arr1 = np.array(ls1)
arr2 = np.array(ls2)
arr3 = arr1+arr2
print(arr3)#numpy의 +연산은 행렬의 +연산을 수행

[5 9 5]


In [ ]:
ls=[1,2,3]
ls2 = ls*3
print(ls2) #리스트*수는 원소를 반복해서 나열

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
arr = np.array(ls)
arr2 = arr*3
print(arr2) #numpy의 ndarray*정수는 행렬*정수 연산을 수행

[3 6 9]


%%time을 마킹하면 수행 시간을 측정해 줍니다.

In [ ]:
%%time
arr = np.arange(100000)

CPU times: user 1.82 ms, sys: 0 ns, total: 1.82 ms
Wall time: 1.4 ms


In [ ]:
%%time
ls = list(range(100000)) 

CPU times: user 4.87 ms, sys: 1.06 ms, total: 5.93 ms
Wall time: 6.02 ms


In [ ]:
arr = np.random.randn(2,3)#2X3 행렬을 생성(원소는 랜덤하게 결정)
print(arr)

[[ 0.63122682 -0.5116836  -0.77854657]
 [-0.10233979  0.47566091  1.48494962]]


In [ ]:
arr2 = arr*3
arr2

array([[ 1.89368046, -1.53505079, -2.3356397 ],
       [-0.30701936,  1.42698272,  4.45484886]])

In [ ]:
arr

array([[ 0.63122682, -0.5116836 , -0.77854657],
       [-0.10233979,  0.47566091,  1.48494962]])

In [ ]:
arr.shape #구조 확인

(2, 3)

In [ ]:
arr.ndim #차원 확인

2

In [ ]:
arr.dtype#원소 타입 확인

dtype('float64')

In [ ]:
arr = np.array([1,2,3])
print(arr)
print(arr.dtype)

[1 2 3]
int64


In [ ]:
arr = np.array([1,2,3,4.2]) #정수와 실수로 배열 생성=>모든 정수는 실수로 변환
print(arr)
print(arr.dtype)
print(type(arr[0]))

[1.  2.  3.  4.2]
float64
<class 'numpy.float64'>


In [ ]:
arr = np.array([1,2,3,4.2,'a']) #수와 문자열로 구성=>모두 문자열로 변환
print(arr)
print(arr.dtype)
print(type(arr[0]))

['1' '2' '3' '4.2' 'a']
<U32
<class 'numpy.str_'>


# 다차원 배열 생성

In [ ]:
ls = [1,2,3]
arr = np.array(ls) #리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
ls = [[1,2,3],[2,5,6]]
arr = np.array(ls) #리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))

[[1 2 3]
 [2 5 6]]
<class 'numpy.ndarray'>


In [ ]:
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

구조: (2, 3)
차원: 2
원소 형식: int64


In [ ]:
arr = np.zeros(10)
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
구조: (10,)
차원: 1
원소 형식: float64


In [ ]:
arr = np.zeros((3,6))
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
구조: (3, 6)
차원: 2
원소 형식: float64


In [ ]:
arr = np.ones((3,6))
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
구조: (3, 6)
차원: 2
원소 형식: float64


In [ ]:
arr = np.arange(20)
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
구조: (20,)
차원: 1
원소 형식: int64


In [ ]:
arr = np.arange(3,20,4)
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[ 3  7 11 15 19]
구조: (5,)
차원: 1
원소 형식: int64


# 원소 타입

In [ ]:
arr = np.array([1,2,3])
print(type(arr[0]),type(arr[1]),type(arr[2]))
print(arr.dtype)

<class 'numpy.int64'> <class 'numpy.int64'> <class 'numpy.int64'>
int64


In [ ]:
arr = np.array([1,2,4.2])
print(type(arr[0]),type(arr[1]),type(arr[2]))
print(arr.dtype)

<class 'numpy.float64'> <class 'numpy.float64'> <class 'numpy.float64'>
float64


In [ ]:
arr = np.array([1,2,4.2],dtype=np.int32)#dtype 인자를 이용하여 명시적으로 원소 형식 결정
print(type(arr[0]),type(arr[1]),type(arr[2]))
print(arr.dtype)
print(arr)

<class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'>
int32
[1 2 4]


# 산술 연산

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("====")
arr2 = arr*arr
print(arr2)

[[1 2 3]
 [4 5 6]]
====
[[ 1  4  9]
 [16 25 36]]


In [ ]:
arr2 = arr-arr
print(arr2)

[[0 0 0]
 [0 0 0]]


In [ ]:
arr2 = 1/arr
print(arr2)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [ ]:
arr2 = arr**0.5
print(arr2)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,0,2])
filter = arr1>arr2
print(filter)

[False  True  True]


# 색인 및 슬라이싱

In [ ]:
arr = np.arange(1000)

In [ ]:
print(arr[5:8])

[5 6 7]


In [ ]:
print(arr[:8])

[0 1 2 3 4 5 6 7]


In [ ]:
print(arr[995:])

[995 996 997 998 999]


In [ ]:
print(arr[-5:])

[995 996 997 998 999]


In [ ]:
arr = np.zeros(30)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [ ]:
arr[5:8]=7
print(arr)

[0. 0. 0. 0. 0. 7. 7. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr[0]) 
print(arr[1])
print(arr[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
print(arr[0][2]) 

3


In [ ]:
print(arr[0,2]) 

3


In [ ]:
#소스 배열을 가지고 간단한 실험을 하기 위해서 복사하여 사용하기
cp_arr = arr.copy()
print(cp_arr)
cp_arr[0][1]=8
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
cp_arr = arr #arr과 cp_arr은 같은 개체를 참조
print(cp_arr)
cp_arr[0][1]=8
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr = np.array([1,2,3])

filter = arr>=2
print(filter)

[False  True  True]


In [ ]:
res = arr[filter]
print(res)

[2 3]


In [ ]:
res = arr[~filter]
print(res)

[1]


# 구조 변경

In [ ]:
arr = np.arange(96)
print("구조:",arr.shape)
print("차원:",arr.ndim)

구조: (96,)
차원: 1


In [ ]:
arr2 = arr.reshape((6,16))
print("구조:",arr2.shape)
print("차원:",arr2.ndim)

구조: (6, 16)
차원: 2


In [ ]:
#arr2 = arr.reshape((7,13)) #구조 변경할 때 요소의 개수가 같을 때만 구조 변경할 수 있음
#print("구조:",arr2.shape)
#print("차원:",arr2.ndim)

ValueError: ignored

In [ ]:
arr2 = arr.reshape((6,-1)) #구조 변경 요청할 때 하나의 차원은 -1로 표현 가능(알아서 계산)
print("구조:",arr2.shape)
print("차원:",arr2.ndim)

구조: (6, 16)
차원: 2


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = arr.T
print(arr)
print("====")
print(arr2)

[[1 2 3]
 [4 5 6]]
====
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr2 = arr.transpose() #arr.T와 arr.transpose()는 같은 결과(전치행렬)를 반환한다.
print(arr)
print("====")
print(arr2)

[[1 2 3]
 [4 5 6]]
====
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr2 = np.sqrt(arr)
print(arr2)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr1 = np.random.randn(2,3)
print(arr1)
print("===")
arr2 = np.random.randn(2,3)
print(arr2)

[[ 1.41526783 -1.78901881 -1.17299417]
 [-1.26056084  0.13910386 -0.54477653]]
===
[[ 0.78373639 -0.82574244  0.06202791]
 [-0.95522216  0.32842207  2.10736215]]


In [ ]:
arr3 = np.maximum(arr1,arr2)
print(arr3)

[[ 1.41526783 -0.82574244  0.06202791]
 [-0.95522216  0.32842207  2.10736215]]


# Numpy 안으로

In [ ]:
#잠시 파이썬 기본 문법 - 리스트 컴프리헨션
xs = [x*x+2*x+3 for x in range(1,10)] #리스트 컴프리헨션
print(xs)

[6, 11, 18, 27, 38, 51, 66, 83, 102]


In [ ]:
xs=[]
for x in range(1,10):
  xs.append(x*x+2*x+3)
print(xs)

[6, 11, 18, 27, 38, 51, 66, 83, 102]


In [ ]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

In [ ]:
#파이썬 기초 문법 - zip 사용 예
ls1=[1,2,3]
ls2=['가','나','다']
for e1, e2 in zip(ls1,ls2):
  print(e1,e2)

1 가
2 나
3 다


In [ ]:
#리스트 컴프리헨션
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [ ]:
result = np.where(cond,xarr,yarr)
print(result)

[1.1 2.2 1.3 1.4 2.5]


In [ ]:
result=[]
for x,y,c in zip(xarr,yarr,cond):
  if c:
    result.append(x)
  else:
    result.append(y)
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [ ]:
result = np.where(cond,1,2)
print(result)

[1 2 1 1 2]


In [ ]:
heights = np.random.normal(172.4,5,100)#평균 172.4 표준편차 5인 표본 100개를 생성
print(heights)

In [ ]:
print("평균:",heights.mean()) #print("평균:",np.mean(heights))
print("합계:",heights.sum()) #print("평균:",np.sum(heights))

평균: 172.5403082294257
합계: 172540.30822942572


In [ ]:
h2 = heights.reshape(20,-1)
print("구조:",h2.shape)
print(h2)

구조: (20, 5)
[[166.34868278 167.70545164 168.87729106 180.10681508 177.01796515]
 [175.5536339  164.13094232 178.86755416 178.7050987  174.22857141]
 [179.89718354 169.9496353  171.06883114 173.6931746  160.47308694]
 [164.37557686 173.06612146 178.26154814 171.46799815 169.85400013]
 [170.80760461 166.49060057 172.87968366 178.67541645 172.36949371]
 [179.11825145 174.19258124 170.85492721 174.9788753  169.12597437]
 [168.67728646 173.02441736 177.38387279 173.98199054 178.9799077 ]
 [175.89187863 175.02126449 172.91977771 172.22684256 168.6362982 ]
 [166.75472097 172.20937245 172.51813002 171.60751509 177.15248424]
 [169.85895792 176.08976766 167.16948306 173.6485224  168.73300495]
 [181.04061318 171.42544063 165.85286459 175.73457735 168.28331254]
 [179.73062757 167.04910451 165.13630392 164.07843775 173.29090302]
 [164.29510101 173.52992426 170.42794292 177.44550937 169.16909614]
 [177.41640374 169.53075795 172.10669509 176.41055766 177.29440516]
 [180.5532041  174.33670625 175.3498

In [ ]:
print("평균(축0):",h2.mean(axis=0)) #컬럼 별 평균
print("평균(축1):",h2.mean(axis=1)) #로우 별 평균

평균(축0): [173.2794873  171.40710588 172.74364704 172.88329971 172.33604239]
평균(축1): [172.01124114 174.2971601  171.01638231 171.40504895 172.2445598
 173.65412191 174.40949497 172.93921232 172.04844455 171.0999472
 172.46736166 169.85707536 170.97351474 174.55176392 173.8574154
 170.45705289 173.59009422 171.15588007 175.32422599 173.23833176]


In [ ]:
print("합계(축0):",h2.sum(axis=0)) #컬럼 별 합계
print("합계(축1):",h2.sum(axis=1)) #로우 별 합계

합계(축0): [3465.58974595 3428.14211757 3454.87294076 3457.66599417 3446.7208479 ]
합계(축1): [860.05620572 871.48580049 855.08191153 857.02524475 861.222799
 868.27060957 872.04747485 864.6960616  860.24222277 855.49973599
 862.33680828 849.28537678 854.86757372 872.75881959 869.28707702
 852.28526444 867.95047111 855.77940035 876.62112997 866.19165882]


In [ ]:
print("분산:",h2.var()) 
print("표준편차:",h2.std())

분산: 21.796294370347404
표준편차: 4.668650165770338


In [ ]:
print("최솟값:",h2.min()) 
print("최댓값:",h2.max())

최솟값: 160.47308694259831
최댓값: 181.92741142774884


In [ ]:
print("최솟값이 있는 위치:",heights.argmin()) 
print("최댓값이 있는 위치:",heights.argmax())
print(heights[heights.argmin()],heights[heights.argmax()])

최솟값이 있는 위치: 14
최댓값이 있는 위치: 92
160.47308694259831 181.92741142774884


In [ ]:
arr= np.array([1,2,4,2,7])
print("누적 합계:",arr.cumsum()) 
print("누적 곱:",arr.cumprod()) 

누적 합계: [ 1  3  7  9 16]
누적 곱: [  1   2   8  16 112]


In [ ]:
arr.sort()
print(arr)

[1 2 2 4 7]


In [ ]:
ua = np.unique(arr)
print(ua)

[1 2 4 7]


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,3],[1,2],[4,5]])
re = x.dot(y)
print(x)
print("===")
print(y)
print("====")
print(re)

[[1 2 3]
 [4 5 6]]
===
[[2 3]
 [1 2]
 [4 5]]
====
[[16 22]
 [37 52]]


# 난수

In [ ]:
for _ in range(10):
  print(np.random.uniform(-2,3))#-2에서 3사이의 랜덤한 실수 반환

0.8392885724189121
0.6205907759186831
0.7968913750072621
2.719277779760926
2.0664532402982436
1.4852163092685928
-1.9534014734513987
1.707262752131562
1.9634297246283028
-0.86771758132282


In [ ]:
for _ in range(20):
  print(np.random.randint(1,5),end=' ')#1에서 5사이의 랜덤한 정수 반환
print()

3 4 4 2 3 2 2 3 3 2 2 3 4 1 1 2 4 4 2 2 


In [ ]:
volan = [1,7,2,8,9]
for _ in range(20):
  print(np.random.choice(volan),end=' ')
print()

8 1 1 8 7 1 2 8 2 2 9 2 8 2 9 1 7 9 8 9 
